In [1]:
import pandas as pd
import requests
import json
from pprint import pprint
import time

# Data Import
Calling API and Importing JSON File

In [2]:
url = "https://services5.arcgis.com/54falWtcpty3V47Z/arcgis/rest/services/general_offenses_year3/FeatureServer/0/query?where=1%3D1&outFields=*&outSR=4326&resultType=standard&f=json"
json = json.loads(requests.get(url).text)

# Displaying JSON File

# Reformating Data
Pulling values from each key and listing them in a seperate variable

In [3]:
Beat = []
Description = []
Grid = []
ObjectID = []
Occurence_Date = []
Offense_Category = []
Offense_Code = []
Offense_Ext = []
Police_District = []
Record_ID = []

for i in range(len(json['features'])):
    for k, v in json['features'][i]['attributes'].items():
        if k == 'Beat':
            Beat.append(v)
        if k == 'Description':
            Description.append(v)
        if k == 'Grid':
            Grid.append(v)
        if k == 'OBJECTID':
            ObjectID.append(v)
        if k == 'Occurence_Date':
            Occurence_Date.append(v)
        if k == 'Offense_Category':
            Offense_Category.append(v)
        if k == 'Offense_Code':
            Offense_Code.append(v)
        if k == 'Offense_Ext':
            Offense_Ext.append(v)
        if k == 'Police_District':
            Police_District.append(v)
        if k == 'Record_ID':
            Record_ID.append(v)

# Creating New Dictionary
Creating a dictionary with our new lists

In [4]:
crime_dict = {'Beat': Beat,
 'Description': Description,
 'Grid': Grid,
 'ObjectID': ObjectID,
 'Occurence_Date': Occurence_Date,
 'Offense_Category': Offense_Category,
 'Offense_Code': Offense_Code,
 'Offense_Ext': Offense_Ext,
 'Police_District': Police_District,
 'Record_ID': Record_ID}

# Transforming Dictionary to DataFrame

In [5]:
crime_df = pd.DataFrame(crime_dict).set_index('ObjectID')

In [6]:
crime_df = crime_df.loc[crime_df['Beat'] != 'UI']
crime_df.dropna(inplace=True)
crime_df.reset_index(drop=True, inplace=True)
crime_df.count()

Beat                13851
Description         13851
Grid                13851
Occurence_Date      13851
Offense_Category    13851
Offense_Code        13851
Offense_Ext         13851
Police_District     13851
Record_ID           13851
dtype: int64

In [7]:
# Reviewing data types
crime_df.dtypes

Beat                object
Description         object
Grid                object
Occurence_Date       int64
Offense_Category    object
Offense_Code        object
Offense_Ext         object
Police_District     object
Record_ID           object
dtype: object

# Converting Data Types

In [8]:
crime_df['Grid'] = crime_df['Grid'].astype('int')
crime_df['Occurence_Date'] = crime_df['Occurence_Date'].astype('str')
crime_df['Offense_Code'] = crime_df['Offense_Code'].astype('int')
crime_df['Police_District'] = crime_df['Police_District'].astype('int')
crime_df['Record_ID'] = crime_df['Record_ID'].astype('int')

In [9]:
crime_df.dtypes

Beat                object
Description         object
Grid                 int64
Occurence_Date      object
Offense_Category    object
Offense_Code         int64
Offense_Ext         object
Police_District      int64
Record_ID            int64
dtype: object

In [10]:
crime_df

,Beat,Description,Grid,Occurence_Date,Offense_Category,Offense_Code,Offense_Ext,Police_District,Record_ID
0,6B,246 PC SHOOT OCCUP DWELL/VEH,1401,1577866620000,WEAPON OFFENSE,5213,4,6,1429759
1,2B,594(A)(2) VANDALISM-DAMAGE,564,1577872380000,VANDALISM,2999,33,2,1429760
2,3M,69 PC RESIST/OBSTRCT EXEC OFC,741,1577872080000,OBSTRUCTING,4801,5,3,1429779
3,6C,10851(A)VC TAKE VEH W/O OWNER,1441,1577876400000,STOLEN VEHICLE,2404,0,6,1429804
4,3B,23153(A) DUI ALCOHOL W/INJ,777,1577875380000,TRAFFIC,5404,10,3,1429831
...,...,...,...,...,...,...,...,...,...
13846,5C,TRAFFIC ACCIDENT-INJURY,1606,1589097000000,TRAFFIC,5400,0,5,1458730
13847,2B,484 PETTY THEFT/LICENSE PLATE,546,1588887000000,LARCENY,2399,4,2,1458735
13848,5B,594(B)(1) VANDL $10000 OR M0RE,1621,1589961660000,VANDALISM,2999,02,5,1458745
13849,2C,594(B)(2)(A) VANDAL UNDER $400,615,1590534000000,VANDALISM,2999,05,2,1458821
13850,2C,594(B)(1) VANDL $10000 OR M0RE,620,1590564000000,VANDALISM,2999,02,2,1458824

In [11]:
Occurence_Date = []
for i in range(len(crime_df)):
        trimmed_unix = crime_df['Occurence_Date'][i][0:10]
        date_time = time.strftime('%a %m-%d-%Y, %I:%M:%S %p', time.localtime(int(trimmed_unix)))
        Occurence_Date.append(date_time)

crime_df['Occurence_Date'] = Occurence_Date

In [12]:
crime_df

,Beat,Description,Grid,Occurence_Date,Offense_Category,Offense_Code,Offense_Ext,Police_District,Record_ID
0,6B,246 PC SHOOT OCCUP DWELL/VEH,1401,"Wed 01-01-2020, 12:17:00 AM",WEAPON OFFENSE,5213,4,6,1429759
1,2B,594(A)(2) VANDALISM-DAMAGE,564,"Wed 01-01-2020, 01:53:00 AM",VANDALISM,2999,33,2,1429760
2,3M,69 PC RESIST/OBSTRCT EXEC OFC,741,"Wed 01-01-2020, 01:48:00 AM",OBSTRUCTING,4801,5,3,1429779
3,6C,10851(A)VC TAKE VEH W/O OWNER,1441,"Wed 01-01-2020, 03:00:00 AM",STOLEN VEHICLE,2404,0,6,1429804
4,3B,23153(A) DUI ALCOHOL W/INJ,777,"Wed 01-01-2020, 02:43:00 AM",TRAFFIC,5404,10,3,1429831
...,...,...,...,...,...,...,...,...,...
13846,5C,TRAFFIC ACCIDENT-INJURY,1606,"Sun 05-10-2020, 12:50:00 AM",TRAFFIC,5400,0,5,1458730
13847,2B,484 PETTY THEFT/LICENSE PLATE,546,"Thu 05-07-2020, 02:30:00 PM",LARCENY,2399,4,2,1458735
13848,5B,594(B)(1) VANDL $10000 OR M0RE,1621,"Wed 05-20-2020, 01:01:00 AM",VANDALISM,2999,02,5,1458745
13849,2C,594(B)(2)(A) VANDAL UNDER $400,615,"Tue 05-26-2020, 04:00:00 PM",VANDALISM,2999,05,2,1458821
13850,2C,594(B)(1) VANDL $10000 OR M0RE,620,"Wed 05-27-2020, 12:20:00 AM",VANDALISM,2999,02,2,1458824

# Placing Data Frame into a CSV

In [13]:
crime_df.to_csv('sac_crime', index=False)